import type { DecisionCardDef } from '../simulation'
import { SITE_NAME } from './site'

/**
 * Hand-authored set of Mercury-era decision cards. Every card is severity
 * 'flag' — it queues in the status menu without stopping the clock. Cards
 * recur after `cooldownDays` so the pool doesn't run dry over a long
 * campaign. About half carry a `deadlineDays` — the rest can sit in the
 * queue indefinitely.
 */
export const CARD_POOL: DecisionCardDef[] = [
  {
    id: 'congressional-hearing',
    title: 'Congressional Budget Hearing',
    description:
      'A subcommittee wants testimony on program spending before the next appropriation. How do you play it?',
    severity: 'flag',
    site: SITE_NAME,
    department: 'budget',
    availableFromDay: 3,
    cooldownDays: 30,
    deadlineDays: 10,
    onExpireOptionId: 'cautious',
    options: [
      {
        id: 'confident',
        label: 'Project confidence, ask for more',
        description: 'Sentiment rises with a bold pitch, but funds are held to the same target if you fall short.',
        effects: { sentiment: 4, budget: -1000 },
      },
      {
        id: 'cautious',
        label: 'Underpromise, protect the budget',
        description: 'A modest ask keeps the books safe but wins no headlines.',
        effects: { sentiment: -1, budget: 2000 },
      },
    ],
  },
  {
    id: 'contractor-delay',
    title: 'Contractor Delivery Delay',
    description: 'The booster fabrication contractor is behind schedule on a critical structural component.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 6,
    cooldownDays: 25,
    options: [
      {
        id: 'expedite',
        label: 'Pay a rush premium',
        description: 'Spend funds to keep hardware stores on track.',
        effects: { budget: -1500, materials: 15 },
      },
      {
        id: 'wait',
        label: 'Absorb the delay',
        description: 'Save the money and take the hit to crew readiness from idle schedules.',
        effects: { crewReadiness: -5 },
      },
    ],
  },
  {
    id: 'press-exclusive',
    title: 'Life-Style Magazine Exclusive',
    description: 'A glossy national magazine wants exclusive access to the program for a feature spread.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'press',
    availableFromDay: 10,
    cooldownDays: 25,
    deadlineDays: 6,
    onExpireOptionId: 'decline',
    options: [
      {
        id: 'grant-access',
        label: 'Grant full access',
        description: 'A generous Sentiment bump, at the cost of a distracted week for crew and staff.',
        effects: { sentiment: 6, crewReadiness: -3 },
      },
      {
        id: 'decline',
        label: 'Decline politely',
        description: 'Keep focus on the work. No swing either way.',
        effects: {},
      },
    ],
  },
  {
    id: 'public-tour-mishap',
    title: 'Public Tour Mishap',
    description: 'A visiting tour group wandered too close to the gantry. Someone spilled coffee on a console.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'press',
    availableFromDay: 14,
    cooldownDays: 20,
    options: [
      {
        id: 'laugh-it-off',
        label: 'Laugh it off publicly',
        description: 'The self-deprecating angle plays well with the press.',
        effects: { sentiment: 2 },
      },
      {
        id: 'tighten-security',
        label: 'Tighten tour security',
        description: 'Spend a little to prevent a repeat; no immediate Sentiment change.',
        effects: { budget: -300 },
      },
    ],
  },
  {
    id: 'weather-delay-supplies',
    title: 'Barge Delayed by Weather',
    description: 'Rough seas held up the materials barge for three days.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 18,
    cooldownDays: 22,
    options: [
      {
        id: 'air-freight',
        label: 'Air-freight the shortfall',
        description: 'Expensive, but keeps materials flowing.',
        effects: { budget: -800, materials: 10 },
      },
      {
        id: 'ride-it-out',
        label: 'Ride it out',
        description: 'No cost, but stores run thinner this week.',
        effects: { materials: -10 },
      },
    ],
  },
  {
    id: 'safety-inspection',
    title: 'Independent Safety Inspection',
    description: 'A review board has requested full access to inspect hardware and paperwork.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 22,
    cooldownDays: 30,
    deadlineDays: 8,
    onExpireOptionId: 'limit-access',
    options: [
      {
        id: 'welcome-scrutiny',
        label: 'Welcome the scrutiny',
        description: 'Pay for the disruption, but a clean bill of health plays well publicly.',
        effects: { budget: -1200, sentiment: 3 },
      },
      {
        id: 'limit-access',
        label: 'Limit their access',
        description: 'Keeps costs down, but looks defensive if word gets out.',
        effects: { sentiment: -2 },
      },
    ],
  },
  {
    id: 'labor-dispute',
    title: 'Ground Crew Labor Dispute',
    description: 'Technicians and pad crew are pushing for better shift conditions ahead of a busy stretch.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'personnel',
    availableFromDay: 26,
    cooldownDays: 35,
    deadlineDays: 8,
    onExpireOptionId: 'hold-firm',
    options: [
      {
        id: 'meet-demands',
        label: 'Meet their demands',
        description: 'Costs money now, but crew morale and readiness improve.',
        effects: { budget: -1000, crewReadiness: 8 },
      },
      {
        id: 'hold-firm',
        label: 'Hold firm on the budget',
        description: 'Saves money, but morale and public sympathy both take a hit.',
        effects: { crewReadiness: -6, sentiment: -2 },
      },
    ],
  },
  {
    id: 'recruiting-drive',
    title: 'Recruiting Drive Funding',
    description: 'Personnel wants a bigger budget for the next round of ground-crew recruiting.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'personnel',
    availableFromDay: 30,
    cooldownDays: 30,
    deadlineDays: 10,
    onExpireOptionId: 'trim-it',
    options: [
      {
        id: 'fund-it',
        label: 'Fund the expanded drive',
        description: 'Spend now to build a deeper bench of crew readiness.',
        effects: { budget: -900, crewReadiness: 6 },
      },
      {
        id: 'trim-it',
        label: 'Keep the drive modest',
        description: 'No cost, no gain — the bench stays thin.',
        effects: {},
      },
    ],
  },
  {
    id: 'surplus-parts',
    title: 'War-Surplus Parts Lot',
    description: 'A depot is auctioning off a lot of aerospace-grade surplus hardware.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 34,
    cooldownDays: 28,
    options: [
      {
        id: 'buy-the-lot',
        label: 'Buy the whole lot',
        description: 'A good price on a bulk restock of materials.',
        effects: { budget: -600, materials: 20 },
      },
      {
        id: 'pass',
        label: 'Pass on it',
        description: 'No change either way.',
        effects: {},
      },
    ],
  },
  {
    id: 'dignitary-visit',
    title: 'Foreign Dignitary Visit',
    description: 'A visiting head of state has requested an unscheduled tour of the facility.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'press',
    availableFromDay: 38,
    cooldownDays: 30,
    deadlineDays: 5,
    onExpireOptionId: 'standard-tour',
    options: [
      {
        id: 'red-carpet',
        label: 'Roll out the red carpet',
        description: 'A real Sentiment win, at real expense.',
        effects: { budget: -1800, sentiment: 7 },
      },
      {
        id: 'standard-tour',
        label: 'Give the standard tour',
        description: 'Cheap and polite, with a smaller Sentiment bump.',
        effects: { sentiment: 2 },
      },
    ],
  },
  {
    id: 'editorial-cartoon',
    title: 'Unflattering Editorial Cartoon',
    description: 'A widely syndicated cartoon pokes fun at a recent delay.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'press',
    availableFromDay: 42,
    cooldownDays: 24,
    deadlineDays: 4,
    onExpireOptionId: 'ignore-it',
    options: [
      {
        id: 'respond-publicly',
        label: 'Respond with good humor',
        description: 'A gracious public response limits the damage.',
        effects: { sentiment: -1 },
      },
      {
        id: 'ignore-it',
        label: 'Ignore it',
        description: "Don't dignify it with a response, but the jab lands harder.",
        effects: { sentiment: -3 },
      },
    ],
  },
  {
    id: 'heatwave',
    title: 'Summer Heatwave',
    description: 'A prolonged heatwave is straining cooling systems and outdoor material stores.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 46,
    cooldownDays: 26,
    options: [
      {
        id: 'extra-cooling',
        label: 'Run emergency cooling',
        description: 'Protects hardware stores at a real cost.',
        effects: { budget: -500 },
      },
      {
        id: 'risk-it',
        label: 'Risk it',
        description: 'Save the money; some stored materials spoil in the heat.',
        effects: { materials: -12 },
      },
    ],
  },
  {
    id: 'rival-milestone-reaction',
    title: 'Rival Program Achieves a Milestone',
    description: 'News breaks that the rival program reached a milestone first. The press wants a reaction.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'press',
    availableFromDay: 50,
    cooldownDays: 32,
    deadlineDays: 6,
    onExpireOptionId: 'downplay-it',
    options: [
      {
        id: 'rally-the-public',
        label: 'Rally the public around the challenge',
        description: 'A messaging push turns the comparison into motivation.',
        effects: { sentiment: 3, budget: -500 },
      },
      {
        id: 'downplay-it',
        label: 'Downplay the comparison',
        description: 'No cost, but the unanswered story lingers.',
        effects: { sentiment: -2 },
      },
    ],
  },
  {
    id: 'training-mishap',
    title: 'Minor Training Mishap',
    description: 'A simulator run goes wrong — no injuries, but a real scare on the training floor.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'astronaut-corps',
    availableFromDay: 54,
    cooldownDays: 28,
    options: [
      {
        id: 'full-review',
        label: 'Run a full incident review',
        description: 'Costs time and money, but the lessons stick.',
        effects: { budget: -700, crewReadiness: 5 },
      },
      {
        id: 'move-on',
        label: 'Quietly move on',
        description: 'No cost, but quiet doubt lingers on the floor.',
        effects: { crewReadiness: -4 },
      },
    ],
  },
  {
    id: 'astronaut-public-appearance',
    title: 'Astronaut Requested for a Public Appearance',
    description: 'A civic group wants one of the active roster for a high-visibility appearance.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'astronaut-corps',
    availableFromDay: 58,
    cooldownDays: 26,
    deadlineDays: 5,
    onExpireOptionId: 'decline',
    options: [
      {
        id: 'send-them',
        label: 'Send them',
        description: 'A real Sentiment boost, at the cost of training time.',
        effects: { sentiment: 5, crewReadiness: -4 },
      },
      {
        id: 'decline',
        label: 'Decline, protect the training schedule',
        description: 'No change either way.',
        effects: {},
      },
    ],
  },
  {
    id: 'flight-surgeon-concern',
    title: 'Flight Surgeon Flags a Concern',
    description: 'The flight surgeon recommends a mandatory rest period for ground crew ahead of the next push.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'astronaut-corps',
    availableFromDay: 62,
    cooldownDays: 30,
    deadlineDays: 5,
    onExpireOptionId: 'push-through',
    options: [
      {
        id: 'grant-rest',
        label: 'Grant the rest period',
        description: 'Coverage costs money, but readiness improves.',
        effects: { budget: -400, crewReadiness: 6 },
      },
      {
        id: 'push-through',
        label: 'Push through the schedule',
        description: 'No cost, but fatigue takes its toll.',
        effects: { crewReadiness: -5 },
      },
    ],
  },
  {
    id: 'facility-maintenance',
    title: 'Aging Equipment Needs Maintenance',
    description: 'Ground support equipment is showing its age. Deferred maintenance is starting to add up.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 66,
    cooldownDays: 34,
    options: [
      {
        id: 'full-overhaul',
        label: 'Invest in a full overhaul',
        description: 'A real expense now that pays off in avoided waste.',
        effects: { budget: -1400, materials: 5 },
      },
      {
        id: 'patch-it',
        label: 'Patch it for now',
        description: 'Cheaper today, but the wear catches up.',
        effects: { budget: -200, materials: -8 },
      },
    ],
  },
  {
    id: 'budget-windfall',
    title: 'Unexpected Budget Windfall',
    description: 'A reallocated federal fund lands in the program’s lap ahead of schedule.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'budget',
    availableFromDay: 70,
    cooldownDays: 40,
    options: [
      {
        id: 'bank-it',
        label: 'Bank it quietly',
        description: 'Keep the full amount, no fanfare.',
        effects: { budget: 2500 },
      },
      {
        id: 'announce-it',
        label: 'Announce it publicly',
        description: 'A smaller net gain, but a Sentiment bump from the good news.',
        effects: { budget: 1500, sentiment: 3 },
      },
    ],
  },
  {
    id: 'suspicious-visitor',
    title: 'Suspicious Visitor Reported at the Perimeter',
    description: 'Security reports someone photographing the fence line before slipping away.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 74,
    cooldownDays: 36,
    options: [
      {
        id: 'investigate-quietly',
        label: 'Investigate quietly',
        description: 'A discreet inquiry, at a modest cost.',
        effects: { budget: -500 },
      },
      {
        id: 'alert-authorities',
        label: 'Alert local authorities publicly',
        description: 'No direct cost, but the story leaks and unsettles the public.',
        effects: { sentiment: -1 },
      },
    ],
  },
  {
    id: 'radar-upgrade-pitch',
    title: 'Meteorologist Pitches a Radar Upgrade',
    description: 'The site meteorologist wants budget for a better weather radar system.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 78,
    cooldownDays: 30,
    options: [
      {
        id: 'fund-upgrade',
        label: 'Fund the upgrade',
        description: 'A real cost, but confidence in the program’s rigor grows.',
        effects: { budget: -1600, sentiment: 2 },
      },
      {
        id: 'table-it',
        label: 'Table it for next cycle',
        description: 'No change either way.',
        effects: {},
      },
    ],
  },
  {
    id: 'employee-suggestion-box',
    title: 'Employee Suggestion Nets a Fix',
    description: 'A technician’s suggestion-box idea turns out to be a genuine efficiency win.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'personnel',
    availableFromDay: 82,
    cooldownDays: 28,
    deadlineDays: 9,
    onExpireOptionId: 'file-it-away',
    options: [
      {
        id: 'adopt-it',
        label: 'Adopt and reward the idea',
        description: 'A small payout for a real materials-efficiency gain.',
        effects: { budget: -300, materials: 12 },
      },
      {
        id: 'file-it-away',
        label: 'File it away',
        description: 'No change either way.',
        effects: {},
      },
    ],
  },
  {
    id: 'congressional-site-visit',
    title: 'Congressional Delegation Site Visit',
    description: 'A delegation from the appropriations committee wants a firsthand look at the program.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'budget',
    availableFromDay: 86,
    cooldownDays: 34,
    deadlineDays: 7,
    onExpireOptionId: 'standard-briefing',
    options: [
      {
        id: 'full-vip-treatment',
        label: 'Full VIP treatment',
        description: 'An expensive show, but it builds real goodwill ahead of the next budget cycle.',
        effects: { budget: -1200, sentiment: 5 },
      },
      {
        id: 'standard-briefing',
        label: 'Standard briefing only',
        description: 'Cheap and polite, with a smaller Sentiment bump.',
        effects: { sentiment: 1 },
      },
    ],
  },
  {
    id: 'spare-capsule-request',
    title: 'Spare Capsule Requested by Museum',
    description: 'A national museum wants a retired test article for permanent display.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'infrastructure',
    availableFromDay: 90,
    cooldownDays: 30,
    options: [
      {
        id: 'donate-it',
        label: 'Donate it',
        description: 'A nice Sentiment story, at the cost of a spare.',
        effects: { sentiment: 4, materials: -5 },
      },
      {
        id: 'keep-it',
        label: 'Keep it for spares',
        description: 'Strip it for parts instead of donating it.',
        effects: { materials: 5 },
      },
    ],
  },
  {
    id: 'overtime-costs',
    title: 'Overtime Costs Mount',
    description: 'Pushing to stay on schedule is burning through the overtime budget fast.',
    severity: 'flag',
    site: SITE_NAME,
    department: 'personnel',
    availableFromDay: 94,
    cooldownDays: 24,
    options: [
      {
        id: 'approve-overtime',
        label: 'Approve the overtime',
        description: 'Costs money, but keeps the schedule and crew readiness on track.',
        effects: { budget: -900, crewReadiness: 3 },
      },
      {
        id: 'hold-the-line',
        label: 'Hold the line on budget',
        description: 'Saves money, but the schedule slips and morale dips.',
        effects: { crewReadiness: -3 },
      },
    ],
  },
]
